# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Everything PC - Beginners Handbook
email: glog2002@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Want to get a grip on the world of PCs? Then this is place for you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bomboclutz.github.io" # the base hostname & protocol for your site
twitter_username: bomboclutz
github_username:  bomboclutz

# Build settings
markdown: kramdown

collections:
  articles:
    output: true
    permalink: /:path/
